        <h1 class="title">Frequently Asked Questions</h1>
        <dl class="faq">
            <dt><p>Did you know that there's more logical fallacies than you have listed on this website?</p></dt>
            <dd><p>Yes, yes we did. The point of the site is to make common logical fallacies easily understood, so listing every single one isn't really what it's about. If you want to learn more about logical fallacies check out <a href="http://www.fallacyfiles.org/taxonomy.html" target="_blank" title="Taxonomy of the Logical Fallacies">this comprehensive interactive list</a> of all the formal and informal fallacies. And also check out <a href="http://youarenotsosmart.com">youarenotsosmart.com</a> - we highly recommend the book version of this blog site for anyone wanting to understand their own mind and, for that matter, other people's&nbsp;minds.</p></dd>
            <dt><p>What's this whole thing about, anyway?</p></dt>
            <dd><p>A while ago I was trying to explain logical fallacies to my two boys (you don't know who I am though, do you? I'm Jesse. Hello.). They're smart enough kids, but, you know, they're still kids - and so I tried to come up with really simple ways of explaining the concepts behind some of the more common fallacies.
            </p><p>I found that distilling a fallacy into a single, simple sentence (without using any big pretentious words) was something of a challenge, but because I'm an ad guy I had some skillz with regard to making sure the lowest common denominator could understand the message (not that my kids are the lowest common denominator, but you get my point). So having simplified the explanations of some of the fallacies, I tried to come up with fun examples to go along with them. Then I thought 'hey, what if I were to make these into a poster infographic type thing that parents could hang on their kids' bedroom walls, and slightly nerdy students could hang in their apartments, and teachers could hang in their classrooms, and internetians could hang next to their computers when they're arguing with people on the interwebs?' And that's how this project began.</p><p>I've come to the conclusion that education is the single most vital, important thing that there is, and this website is my first attempt to bring my background in the dark arts of advertising to bear for a positive purpose - making educational materials that are simple, engaging and effective. If you like the cut of the jibs you see here, then please feel free to <a href="#donate" title="donate">donate money to me</a> which I may spend on future educational websites and things, or possibly on lunch/beer. It's a bit pot luck,&nbsp;really.</p><p></p></dd>
            <dt><p>Can I use the stuff on here to teach my class about logical fallacies?</p></dt>
            <dd><p>Absolutely. In fact <a href="http://yourlogicalfallacyis.com/pdf/Logical_Fallacies_on_A4.pdf" title="PDF" target="_blank">here is a pdf</a> with each of the fallacies on a separate page such that you can divide them up to suit your curriculum. If you want something specific for your class, please <a href="mailto:jesse@yourlogicalfallacyis.com">email me</a> and I'll try to help however I&nbsp;can.</p></dd>
        </dl>
